/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface AddEntitlementCreditResponse
 */
export interface AddEntitlementCreditResponse {
    /**
     * The amount to be added to the credit amount.
     * @type {number}
     * @memberof AddEntitlementCreditResponse
     */
    'creditAmountIncrement'?: number;
    /**
     * 
     * @type {string}
     * @memberof AddEntitlementCreditResponse
     */
    'entitlementID'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddEntitlementCreditResponse
     */
    'entitlementTermID'?: string;
    /**
     * The new credit amount after the increment.
     * @type {number}
     * @memberof AddEntitlementCreditResponse
     */
    'newCreditAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof AddEntitlementCreditResponse
     */
    'organizationID'?: string;
}

