/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface AwsSaasProductDescription
 */
export interface AwsSaasProductDescription {
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDescription
     */
    'AssociatedProducts'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AwsSaasProductDescription
     */
    'Categories'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof AwsSaasProductDescription
     */
    'EuW8Submitted'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof AwsSaasProductDescription
     */
    'Highlights'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDescription
     */
    'LongDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDescription
     */
    'Manufacturer'?: string;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDescription
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDescription
     */
    'ProductTitle'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AwsSaasProductDescription
     */
    'Registered'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof AwsSaasProductDescription
     */
    'SearchKeywords'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDescription
     */
    'ShortDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDescription
     */
    'Sku'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AwsSaasProductDescription
     */
    'UsW9Submitted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDescription
     */
    'Visibility'?: string;
}

