/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AwsSaasProductDescription } from './aws-saas-product-description';
// May contain unused imports in some cases
// @ts-ignore
import { AwsSaasProductDimension } from './aws-saas-product-dimension';
// May contain unused imports in some cases
// @ts-ignore
import { AwsSaasProductPromotionalResources } from './aws-saas-product-promotional-resources';
// May contain unused imports in some cases
// @ts-ignore
import { AwsSaasProductSupportInformation } from './aws-saas-product-support-information';
// May contain unused imports in some cases
// @ts-ignore
import { AwsSaasProductVersion } from './aws-saas-product-version';

/**
 * 
 * @export
 * @interface AwsSaasProduct
 */
export interface AwsSaasProduct {
    /**
     * 
     * @type {AwsSaasProductDescription}
     * @memberof AwsSaasProduct
     */
    'Description'?: AwsSaasProductDescription;
    /**
     * 
     * @type {Array<AwsSaasProductDimension>}
     * @memberof AwsSaasProduct
     */
    'Dimensions'?: Array<AwsSaasProductDimension>;
    /**
     * 
     * @type {AwsSaasProductPromotionalResources}
     * @memberof AwsSaasProduct
     */
    'PromotionalResources'?: AwsSaasProductPromotionalResources;
    /**
     * 
     * @type {AwsSaasProductSupportInformation}
     * @memberof AwsSaasProduct
     */
    'SupportInformation'?: AwsSaasProductSupportInformation;
    /**
     * 
     * @type {Array<AwsSaasProductVersion>}
     * @memberof AwsSaasProduct
     */
    'Versions'?: Array<AwsSaasProductVersion>;
    /**
     * The product Id in AWS Marketplace Data Feed Service.
     * @type {string}
     * @memberof AwsSaasProduct
     */
    'dataFeedProductId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProduct
     */
    'productId'?: string;
}

