/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { CompanyInfo } from './company-info';

/**
 * 
 * @export
 * @interface AwsAccountIdentifier
 */
export interface AwsAccountIdentifier {
    /**
     * The AWS Account ID of the buyer in AWS Marketplace
     * @type {string}
     * @memberof AwsAccountIdentifier
     */
    'awsAccountID'?: string;
    /**
     * The AWS Customer ID of the buyer in AWS Marketplace
     * @type {string}
     * @memberof AwsAccountIdentifier
     */
    'awsCustomerID'?: string;
    /**
     * 
     * @type {CompanyInfo}
     * @memberof AwsAccountIdentifier
     */
    'companyInfo'?: CompanyInfo;
    /**
     * The Account ID in AWS Marketplace Data Feed service
     * @type {string}
     * @memberof AwsAccountIdentifier
     */
    'dataFeedAccountID'?: string;
}

