/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AwsSaasProductAdditionalResource } from './aws-saas-product-additional-resource';

/**
 * 
 * @export
 * @interface AwsSaasProductPromotionalResources
 */
export interface AwsSaasProductPromotionalResources {
    /**
     * 
     * @type {Array<AwsSaasProductAdditionalResource>}
     * @memberof AwsSaasProductPromotionalResources
     */
    'AdditionalResources'?: Array<AwsSaasProductAdditionalResource>;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductPromotionalResources
     */
    'LogoUrl'?: string;
}

