/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface AwsSaasProductDeliveryOption
 */
export interface AwsSaasProductDeliveryOption {
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDeliveryOption
     */
    'FulfillmentUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDeliveryOption
     */
    'Id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDeliveryOption
     */
    'Type'?: string;
}

