/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AwsIntegrationCredential } from './aws-integration-credential';

/**
 * 
 * @export
 * @interface AwsAceIntegration
 */
export interface AwsAceIntegration {
    /**
     * 
     * @type {AwsIntegrationCredential}
     * @memberof AwsAceIntegration
     */
    'credential'?: AwsIntegrationCredential;
    /**
     * The partner ID of the ISV/Seller in AWS Partner Network.
     * @type {string}
     * @memberof AwsAceIntegration
     */
    'partnerId'?: string;
    /**
     * The Name of the S3 bucket for AWS APN Customer Engagement Program (ACE) to sync the leads & opportunities.
     * @type {string}
     * @memberof AwsAceIntegration
     */
    's3BucketName'?: string;
    /**
     * The region of the S3 bucket for AWS APN Customer Engagement Program (ACE) to sync the leads & opportunities.
     * @type {string}
     * @memberof AwsAceIntegration
     */
    's3BucketRegion'?: string;
    /**
     * The secret key used to store the AzureIntegrationCredential in AWS Secret manager. for internal usage only.
     * @type {string}
     * @memberof AwsAceIntegration
     */
    'secretKey'?: string;
}

