/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface AwsSaasProductDimension
 */
export interface AwsSaasProductDimension {
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDimension
     */
    'Description'?: string;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDimension
     */
    'Key'?: string;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDimension
     */
    'Name'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AwsSaasProductDimension
     */
    'Types'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AwsSaasProductDimension
     */
    'Unit'?: string;
}

