/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AzureProductSetup } from './azure-product-setup';
// May contain unused imports in some cases
// @ts-ignore
import { AzureTypeValue } from './azure-type-value';

/**
 * Not original fields. They are populated by other API calls
 * @export
 * @interface AzureProductSetup
 */
export interface AzureProductSetup {
    /**
     * 
     * @type {string}
     * @memberof AzureProductSetup
     */
    'callToAction'?: AzureProductSetupCallToActionEnum;
    /**
     * 
     * @type {Array<AzureTypeValue>}
     * @memberof AzureProductSetup
     */
    'channelStates'?: Array<AzureTypeValue>;
    /**
     * 
     * @type {boolean}
     * @memberof AzureProductSetup
     */
    'enableTestDrive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AzureProductSetup
     */
    'resourceType'?: AzureProductSetupResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AzureProductSetup
     */
    'sellingOption'?: AzureProductSetupSellingOptionEnum;
    /**
     * 
     * @type {string}
     * @memberof AzureProductSetup
     */
    'testDriveType'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductSetup
     */
    'trialUri'?: string;
}

type AzureProductSetupCallToActionEnum = 'free' | 'free-trial' | 'contact-me'
type AzureProductSetupResourceTypeEnum = 'AzureProductSetup'
type AzureProductSetupSellingOptionEnum = 'ListingOnly' | 'ListAndSell'


