/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface AzureIncludedBaseQuantity
 */
export interface AzureIncludedBaseQuantity {
    /**
     * 
     * @type {boolean}
     * @memberof AzureIncludedBaseQuantity
     */
    'isInfinite'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AzureIncludedBaseQuantity
     */
    'quantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof AzureIncludedBaseQuantity
     */
    'recurringUnit'?: AzureIncludedBaseQuantityRecurringUnitEnum;
}

type AzureIncludedBaseQuantityRecurringUnitEnum = 'Monthly' | 'Annual'


