/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface AzureMarketplacePrice
 */
export interface AzureMarketplacePrice {
    /**
     * ISO 4217 currency code
     * @type {string}
     * @memberof AzureMarketplacePrice
     */
    'currency'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AzureMarketplacePrice
     */
    'markets'?: Array<string>;
    /**
     * default 0
     * @type {number}
     * @memberof AzureMarketplacePrice
     */
    'price'?: number;
    /**
     * 
     * @type {any}
     * @memberof AzureMarketplacePrice
     */
    'prices'?: any;
}

