/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface AzureProductListingAsset
 */
export interface AzureProductListingAsset {
    /**
     * 
     * @type {string}
     * @memberof AzureProductListingAsset
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListingAsset
     */
    'fileName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListingAsset
     */
    'fileSasUri'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListingAsset
     */
    'friendlyName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListingAsset
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof AzureProductListingAsset
     */
    'order'?: number;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListingAsset
     */
    'publisherDefinedSasUri'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListingAsset
     */
    'resourceType'?: AzureProductListingAssetResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListingAsset
     */
    'state'?: AzureProductListingAssetStateEnum;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListingAsset
     */
    'type'?: string;
}

type AzureProductListingAssetResourceTypeEnum = 'ListingAsset' | 'ListingImage' | 'ListingVideo'
type AzureProductListingAssetStateEnum = 'PendingUpload' | 'Uploaded' | 'InProcessing' | 'Processed' | 'ProcessFailed'


