/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AzureMarketplacePrivateOfferAcceptanceLink } from './azure-marketplace-private-offer-acceptance-link';
// May contain unused imports in some cases
// @ts-ignore
import { AzureMarketplacePrivateOfferBeneficiary } from './azure-marketplace-private-offer-beneficiary';
// May contain unused imports in some cases
// @ts-ignore
import { AzureMarketplacePrivateOfferPricing } from './azure-marketplace-private-offer-pricing';
// May contain unused imports in some cases
// @ts-ignore
import { AzureMarketplacePrivateOfferPromotionReference } from './azure-marketplace-private-offer-promotion-reference';
// May contain unused imports in some cases
// @ts-ignore
import { AzureMarketplaceValidation } from './azure-marketplace-validation';

/**
 * 
 * @export
 * @interface AzureMarketplacePrivateOffer
 */
export interface AzureMarketplacePrivateOffer {
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    '$schema'?: string;
    /**
     * in format YYYY-MM-DD
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'acceptBy'?: string;
    /**
     * 
     * @type {Array<AzureMarketplacePrivateOfferAcceptanceLink>}
     * @memberof AzureMarketplacePrivateOffer
     */
    'acceptanceLinks'?: Array<AzureMarketplacePrivateOfferAcceptanceLink>;
    /**
     * array of email addresses.
     * @type {Array<AzureMarketplacePrivateOfferBeneficiary>}
     * @memberof AzureMarketplacePrivateOffer
     */
    'beneficiaries'?: Array<AzureMarketplacePrivateOfferBeneficiary>;
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'eTag'?: string;
    /**
     * in format YYYY-MM-DD
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'end'?: string;
    /**
     * in format of \"private-offer/private-offer-durable-id\"
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'id'?: string;
    /**
     * in format YYYY-MM-DD
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'lastModified'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'name'?: string;
    /**
     * array of email addresses of the users to be notified of any changes in the private offer status.
     * @type {Array<string>}
     * @memberof AzureMarketplacePrivateOffer
     */
    'notificationContacts'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'preparedBy'?: string;
    /**
     * Up to 10 pricing entries are allowed.
     * @type {Array<AzureMarketplacePrivateOfferPricing>}
     * @memberof AzureMarketplacePrivateOffer
     */
    'pricing'?: Array<AzureMarketplacePrivateOfferPricing>;
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'privateOfferType'?: AzureMarketplacePrivateOfferPrivateOfferTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'resourceName'?: string;
    /**
     * in format YYYY-MM-DD, if VariableStartDate = true, this field should be empty.
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'start'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'state'?: AzureMarketplacePrivateOfferStateEnum;
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'subState'?: AzureMarketplacePrivateOfferSubStateEnum;
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOffer
     */
    'termsAndConditionsDocSasUrl'?: string;
    /**
     * 
     * @type {AzureMarketplacePrivateOfferPromotionReference}
     * @memberof AzureMarketplacePrivateOffer
     */
    'upgradedFrom'?: AzureMarketplacePrivateOfferPromotionReference;
    /**
     * 
     * @type {Array<AzureMarketplaceValidation>}
     * @memberof AzureMarketplacePrivateOffer
     */
    'validations'?: Array<AzureMarketplaceValidation>;
    /**
     * 
     * @type {boolean}
     * @memberof AzureMarketplacePrivateOffer
     */
    'variableStartDate'?: boolean;
}

type AzureMarketplacePrivateOfferPrivateOfferTypeEnum = 'customerPromotion' | 'cspPromotion'
type AzureMarketplacePrivateOfferStateEnum = 'draft' | 'live' | 'withdrawn' | 'deleted'
type AzureMarketplacePrivateOfferSubStateEnum = 'pendingAcceptance' | 'accepted'


