/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface AzureBuyerInfo
 */
export interface AzureBuyerInfo {
    /**
     * 
     * @type {string}
     * @memberof AzureBuyerInfo
     */
    'billingAccountId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureBuyerInfo
     */
    'customerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureBuyerInfo
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureBuyerInfo
     */
    'lastName'?: string;
}

