/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AzureTypeValue } from './azure-type-value';

/**
 * 
 * @export
 * @interface AzureVariantResource
 */
export interface AzureVariantResource {
    /**
     * 
     * @type {Array<AzureTypeValue>}
     * @memberof AzureVariantResource
     */
    'resources'?: Array<AzureTypeValue>;
    /**
     * 
     * @type {string}
     * @memberof AzureVariantResource
     */
    'variantID'?: string;
}

