/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AzurePendingUpdateInfo } from './azure-pending-update-info';
// May contain unused imports in some cases
// @ts-ignore
import { AzureTypeValue } from './azure-type-value';
// May contain unused imports in some cases
// @ts-ignore
import { AzureVariantResource } from './azure-variant-resource';

/**
 * 
 * @export
 * @interface AzureProductSubmission
 */
export interface AzureProductSubmission {
    /**
     * 
     * @type {boolean}
     * @memberof AzureProductSubmission
     */
    'areResourcesReady'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AzureProductSubmission
     */
    'friendlyName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductSubmission
     */
    'id'?: string;
    /**
     * 
     * @type {AzurePendingUpdateInfo}
     * @memberof AzureProductSubmission
     */
    'pendingUpdateInfo'?: AzurePendingUpdateInfo;
    /**
     * 
     * @type {string}
     * @memberof AzureProductSubmission
     */
    'publishedTimeInUtc'?: string;
    /**
     * 
     * @type {number}
     * @memberof AzureProductSubmission
     */
    'releaseNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof AzureProductSubmission
     */
    'resourceType'?: AzureProductSubmissionResourceTypeEnum;
    /**
     * 
     * @type {Array<AzureTypeValue>}
     * @memberof AzureProductSubmission
     */
    'resources'?: Array<AzureTypeValue>;
    /**
     * 
     * @type {string}
     * @memberof AzureProductSubmission
     */
    'state'?: AzureProductSubmissionStateEnum;
    /**
     * 
     * @type {string}
     * @memberof AzureProductSubmission
     */
    'subState'?: AzureProductSubmissionSubStateEnum;
    /**
     * 
     * @type {Array<AzureTypeValue>}
     * @memberof AzureProductSubmission
     */
    'targets'?: Array<AzureTypeValue>;
    /**
     * 
     * @type {Array<AzureVariantResource>}
     * @memberof AzureProductSubmission
     */
    'variantResources'?: Array<AzureVariantResource>;
}

type AzureProductSubmissionResourceTypeEnum = 'Submission'
type AzureProductSubmissionStateEnum = 'Inprogress' | 'Published'
type AzureProductSubmissionSubStateEnum = 'InDraft' | 'Submitted' | 'Failed' | 'FailedInCertification' | 'ReadyToPublish' | 'Publishing' | 'Published' | 'InStore'


