/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface AzureProductProperty
 */
export interface AzureProductProperty {
    /**
     * 
     * @type {Array<string>}
     * @memberof AzureProductProperty
     */
    'additionalCategories'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AzureProductProperty
     */
    'appVersion'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AzureProductProperty
     */
    'applicableProducts'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AzureProductProperty
     */
    'categories'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AzureProductProperty
     */
    'customAmendments'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AzureProductProperty
     */
    'extendedProperties'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AzureProductProperty
     */
    'globalAmendmentTerms'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AzureProductProperty
     */
    'hideKeys'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AzureProductProperty
     */
    'id'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AzureProductProperty
     */
    'industries'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AzureProductProperty
     */
    'leveledCategories'?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AzureProductProperty
     */
    'leveledIndustries'?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof AzureProductProperty
     */
    'marketingOnlyChange'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof AzureProductProperty
     */
    'productTags'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AzureProductProperty
     */
    'resourceType'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductProperty
     */
    'submissionVersion'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductProperty
     */
    'termsOfUse'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AzureProductProperty
     */
    'useEnterpriseContract'?: boolean;
}

