/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AzureValidationResult } from './azure-validation-result';

/**
 * 
 * @export
 * @interface AzureGovernmentCertification
 */
export interface AzureGovernmentCertification {
    /**
     * 
     * @type {string}
     * @memberof AzureGovernmentCertification
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureGovernmentCertification
     */
    'uri'?: string;
    /**
     * 
     * @type {Array<AzureValidationResult>}
     * @memberof AzureGovernmentCertification
     */
    'validationResults'?: Array<AzureValidationResult>;
}

