/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AzureMarketplaceValidation } from './azure-marketplace-validation';
// May contain unused imports in some cases
// @ts-ignore
import { AzurePriceAndAvailabilityPrivateOfferPrice } from './azure-price-and-availability-private-offer-price';

/**
 * 
 * @export
 * @interface AzurePriceAndAvailabilityPrivateOfferPlan
 */
export interface AzurePriceAndAvailabilityPrivateOfferPlan {
    /**
     * 
     * @type {string}
     * @memberof AzurePriceAndAvailabilityPrivateOfferPlan
     */
    '$schema'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzurePriceAndAvailabilityPrivateOfferPlan
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzurePriceAndAvailabilityPrivateOfferPlan
     */
    'plan'?: string;
    /**
     * 
     * @type {AzurePriceAndAvailabilityPrivateOfferPrice}
     * @memberof AzurePriceAndAvailabilityPrivateOfferPlan
     */
    'pricing'?: AzurePriceAndAvailabilityPrivateOfferPrice;
    /**
     * 
     * @type {string}
     * @memberof AzurePriceAndAvailabilityPrivateOfferPlan
     */
    'product'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzurePriceAndAvailabilityPrivateOfferPlan
     */
    'resourceName'?: string;
    /**
     * 
     * @type {Array<AzureMarketplaceValidation>}
     * @memberof AzurePriceAndAvailabilityPrivateOfferPlan
     */
    'validations'?: Array<AzureMarketplaceValidation>;
}

