/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface AzureListingContact
 */
export interface AzureListingContact {
    /**
     * 
     * @type {string}
     * @memberof AzureListingContact
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureListingContact
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureListingContact
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureListingContact
     */
    'type'?: AzureListingContactTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AzureListingContact
     */
    'uri'?: string;
}

type AzureListingContactTypeEnum = 'CustomerSupport' | 'Engineering' | 'ChannelManager'


