/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AzureLocalizedTimeRange } from './azure-localized-time-range';

/**
 * 
 * @export
 * @interface AzureProductVariantTrial
 */
export interface AzureProductVariantTrial {
    /**
     * 
     * @type {AzureLocalizedTimeRange}
     * @memberof AzureProductVariantTrial
     */
    'dateTimeRange'?: AzureLocalizedTimeRange;
    /**
     * 
     * @type {number}
     * @memberof AzureProductVariantTrial
     */
    'duration'?: number;
    /**
     * 
     * @type {string}
     * @memberof AzureProductVariantTrial
     */
    'durationType'?: AzureProductVariantTrialDurationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AzureProductVariantTrial
     */
    'type'?: AzureProductVariantTrialTypeEnum;
}

type AzureProductVariantTrialDurationTypeEnum = 'Minute' | 'Days' | 'Months'
type AzureProductVariantTrialTypeEnum = 'NoTrial' | 'TimedAccess' | 'TimedUsage' | 'Unlimited'


