/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface AzurePriceAndAvailabilityPrivateOfferCustomMeters
 */
export interface AzurePriceAndAvailabilityPrivateOfferCustomMeters {
    /**
     * One of PriceAndAvailabilityCustomMeter_USD or PriceAndAvailabilityCustomMeter_PerMarket
     * @type {any}
     * @memberof AzurePriceAndAvailabilityPrivateOfferCustomMeters
     */
    'meters'?: any;
    /**
     * default \"usd\"
     * @type {string}
     * @memberof AzurePriceAndAvailabilityPrivateOfferCustomMeters
     */
    'priceInputOption'?: AzurePriceAndAvailabilityPrivateOfferCustomMetersPriceInputOptionEnum;
}

type AzurePriceAndAvailabilityPrivateOfferCustomMetersPriceInputOptionEnum = 'perMarket' | 'usd'


