/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AzureListingContact } from './azure-listing-contact';
// May contain unused imports in some cases
// @ts-ignore
import { AzureListingUri } from './azure-listing-uri';
// May contain unused imports in some cases
// @ts-ignore
import { AzureProductListingAsset } from './azure-product-listing-asset';

/**
 * 
 * @export
 * @interface AzureProductListing
 */
export interface AzureProductListing {
    /**
     * 
     * @type {string}
     * @memberof AzureProductListing
     */
    'summary'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListing
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListing
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListing
     */
    'accessInformation'?: string;
    /**
     * Not original fields. They are populated by other API calls
     * @type {Array<AzureProductListingAsset>}
     * @memberof AzureProductListing
     */
    'assets'?: Array<AzureProductListingAsset>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AzureProductListing
     */
    'compatibleProducts'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListing
     */
    'gettingStartedInstructions'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListing
     */
    'id'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AzureProductListing
     */
    'keywords'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListing
     */
    'languageCode'?: string;
    /**
     * 
     * @type {Array<AzureListingContact>}
     * @memberof AzureProductListing
     */
    'listingContacts'?: Array<AzureListingContact>;
    /**
     * 
     * @type {Array<AzureListingUri>}
     * @memberof AzureProductListing
     */
    'listingUris'?: Array<AzureListingUri>;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListing
     */
    'productDisplayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListing
     */
    'publisherName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListing
     */
    'resourceType'?: AzureProductListingResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AzureProductListing
     */
    'shortDescription'?: string;
}

type AzureProductListingResourceTypeEnum = 'AzureListing'


