/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AzureMarketplacePrivateOfferPricingOriginalPlan } from './azure-marketplace-private-offer-pricing-original-plan';
// May contain unused imports in some cases
// @ts-ignore
import { AzureMarketplacePrivateOfferPricingPrivateOfferPlan } from './azure-marketplace-private-offer-pricing-private-offer-plan';

/**
 * 
 * @export
 * @interface AzureMarketplacePrivateOfferPricing
 */
export interface AzureMarketplacePrivateOfferPricing {
    /**
     * between 0 and 100
     * @type {number}
     * @memberof AzureMarketplacePrivateOfferPricing
     */
    'discountPercentage'?: number;
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOfferPricing
     */
    'discountType'?: AzureMarketplacePrivateOfferPricingDiscountTypeEnum;
    /**
     * 
     * @type {AzureMarketplacePrivateOfferPricingOriginalPlan}
     * @memberof AzureMarketplacePrivateOfferPricing
     */
    'originalPlan'?: AzureMarketplacePrivateOfferPricingOriginalPlan;
    /**
     * in format of \"plan/product-durable-id/plan-durable-id\"
     * @type {string}
     * @memberof AzureMarketplacePrivateOfferPricing
     */
    'plan'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOfferPricing
     */
    'planName'?: string;
    /**
     * The type of the plan, FLAT_RATE or PER_USER.
     * @type {string}
     * @memberof AzureMarketplacePrivateOfferPricing
     */
    'planType'?: AzureMarketplacePrivateOfferPricingPlanTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOfferPricing
     */
    'priceDetails'?: string;
    /**
     * 
     * @type {AzureMarketplacePrivateOfferPricingPrivateOfferPlan}
     * @memberof AzureMarketplacePrivateOfferPricing
     */
    'privateOfferPlan'?: AzureMarketplacePrivateOfferPricingPrivateOfferPlan;
    /**
     * in format of \"product/product-durable-id\"
     * @type {string}
     * @memberof AzureMarketplacePrivateOfferPricing
     */
    'product'?: string;
    /**
     * 
     * @type {string}
     * @memberof AzureMarketplacePrivateOfferPricing
     */
    'sugerOfferId'?: string;
}

type AzureMarketplacePrivateOfferPricingDiscountTypeEnum = 'percentage' | 'absolute'
type AzureMarketplacePrivateOfferPricingPlanTypeEnum = 'FLAT_RATE' | 'PER_USER'


