/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AzureADIdentifier } from './azure-adidentifier';
// May contain unused imports in some cases
// @ts-ignore
import { AzureBuyerInfo } from './azure-buyer-info';
// May contain unused imports in some cases
// @ts-ignore
import { CompanyInfo } from './company-info';

/**
 * Buyer from Azure Marketplace
 * @export
 * @interface BuyerInfoAzureBuyer
 */
export interface BuyerInfoAzureBuyer {
    /**
     * 
     * @type {AzureBuyerInfo}
     * @memberof BuyerInfoAzureBuyer
     */
    'buyerInfo'?: AzureBuyerInfo;
    /**
     * 
     * @type {CompanyInfo}
     * @memberof BuyerInfoAzureBuyer
     */
    'companyInfo'?: CompanyInfo;
    /**
     * Email address
     * @type {string}
     * @memberof BuyerInfoAzureBuyer
     */
    'emailId'?: string;
    /**
     * 
     * @type {string}
     * @memberof BuyerInfoAzureBuyer
     */
    'objectId'?: string;
    /**
     * ID of the user, used as External ID of suger IdentityBuyer.
     * @type {string}
     * @memberof BuyerInfoAzureBuyer
     */
    'puid'?: string;
    /**
     * 
     * @type {string}
     * @memberof BuyerInfoAzureBuyer
     */
    'tenantId'?: string;
}

