/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface CompanyInfo
 */
export interface CompanyInfo {
    /**
     * 
     * @type {string}
     * @memberof CompanyInfo
     */
    'addressLine1'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyInfo
     */
    'addressLine2'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyInfo
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyInfo
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyInfo
     */
    'emailDomain'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyInfo
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyInfo
     */
    'postalCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyInfo
     */
    'state'?: string;
}

