/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AzureMarketplaceSubscription } from './azure-marketplace-subscription';
// May contain unused imports in some cases
// @ts-ignore
import { CommitDimension } from './commit-dimension';
// May contain unused imports in some cases
// @ts-ignore
import { EulaType } from './eula-type';
// May contain unused imports in some cases
// @ts-ignore
import { GcpMarketplaceEntitlement } from './gcp-marketplace-entitlement';
// May contain unused imports in some cases
// @ts-ignore
import { GcpPurchasePlan } from './gcp-purchase-plan';
// May contain unused imports in some cases
// @ts-ignore
import { MeteringDimension } from './metering-dimension';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentInstallment } from './payment-installment';
// May contain unused imports in some cases
// @ts-ignore
import { TypesEntitlement } from './types-entitlement';

/**
 * 
 * @export
 * @interface EntitlementInfo
 */
export interface EntitlementInfo {
    /**
     * Is this Entitlement Auto Renew enabled.
     * @type {boolean}
     * @memberof EntitlementInfo
     */
    'autoRenew'?: boolean;
    /**
     * Nullable. AWS Entitlements from AWS Marketplace.
     * @type {Array<TypesEntitlement>}
     * @memberof EntitlementInfo
     */
    'awsEntitlements'?: Array<TypesEntitlement>;
    /**
     * Nullable. Azure Subscriptions from Azure Marketplace.
     * @type {Array<AzureMarketplaceSubscription>}
     * @memberof EntitlementInfo
     */
    'azureSubscriptions'?: Array<AzureMarketplaceSubscription>;
    /**
     * The amount that the seller can collect. It excludes the marketplace commision fee.
     * @type {number}
     * @memberof EntitlementInfo
     */
    'collectableAmount'?: number;
    /**
     * The amount that the buyer has committed to pay. It can be the sum of payment installments if applicable.
     * @type {number}
     * @memberof EntitlementInfo
     */
    'commitAmount'?: number;
    /**
     * The dimensions for commit.
     * @type {Array<CommitDimension>}
     * @memberof EntitlementInfo
     */
    'commits'?: Array<CommitDimension>;
    /**
     * The default Currency is USD.
     * @type {string}
     * @memberof EntitlementInfo
     */
    'currency'?: string;
    /**
     * The dimensions for usage-based metering.
     * @type {Array<MeteringDimension>}
     * @memberof EntitlementInfo
     */
    'dimensions'?: Array<MeteringDimension>;
    /**
     * The amount that has been disbursed to the seller account.
     * @type {number}
     * @memberof EntitlementInfo
     */
    'disbursedAmount'?: number;
    /**
     * The rate of discount (0 ~ 1.0), such as 0.1 which is 10% off. 0 which is no discount.
     * @type {number}
     * @memberof EntitlementInfo
     */
    'discount'?: number;
    /**
     * 
     * @type {EulaType}
     * @memberof EntitlementInfo
     */
    'eulaType'?: EulaType;
    /**
     * 
     * @type {string}
     * @memberof EntitlementInfo
     */
    'eulaUrl'?: string;
    /**
     * Nullable. GCP Entitlements from GCP Marketplace.
     * @type {Array<GcpMarketplaceEntitlement>}
     * @memberof EntitlementInfo
     */
    'gcpEntitlements'?: Array<GcpMarketplaceEntitlement>;
    /**
     * Only applicable for GCP Marketplace Entitlements.
     * @type {Array<GcpPurchasePlan>}
     * @memberof EntitlementInfo
     */
    'gcpPlans'?: Array<GcpPurchasePlan>;
    /**
     * The amount that the buyer has got invoiced.
     * @type {number}
     * @memberof EntitlementInfo
     */
    'invoicedAmount'?: number;
    /**
     * For flexible payment schedules
     * @type {Array<PaymentInstallment>}
     * @memberof EntitlementInfo
     */
    'paymentInstallments'?: Array<PaymentInstallment>;
    /**
     * 
     * @type {string}
     * @memberof EntitlementInfo
     */
    'refundCancelationPolicy'?: string;
    /**
     * 
     * @type {string}
     * @memberof EntitlementInfo
     */
    'sellerNotes'?: string;
}

