/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { EntitlementTermType } from './entitlement-term-type';

/**
 * 
 * @export
 * @interface EntitlementTermInfo
 */
export interface EntitlementTermInfo {
    /**
     * The decimal part of the dimension quantity, in format of <dimensionKey, decimalPart> It is used to save the decimal part of the dimension quantity for AWS Marketplace only. Because AWS Marketplace only accepts integer for dimension quantity. If the dimension quantity is a decimal number, we need to save the decimal part for future use.
     * @type {{ [key: string]: number; }}
     * @memberof EntitlementTermInfo
     */
    'dimensionQuantityDecimalParts'?: { [key: string]: number; };
    /**
     * 
     * @type {EntitlementTermType}
     * @memberof EntitlementTermInfo
     */
    'type'?: EntitlementTermType;
}

