/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { CompanyInfo } from './company-info';
// May contain unused imports in some cases
// @ts-ignore
import { GcpMarketplaceUserAccountApproval } from './gcp-marketplace-user-account-approval';
// May contain unused imports in some cases
// @ts-ignore
import { GcpMarketplaceUserAccountState } from './gcp-marketplace-user-account-state';
// May contain unused imports in some cases
// @ts-ignore
import { GcpUserInfo } from './gcp-user-info';

/**
 * 
 * @export
 * @interface GcpMarketplaceUserAccount
 */
export interface GcpMarketplaceUserAccount {
    /**
     * The approvals for this account, that are permitted or have been completed.
     * @type {Array<GcpMarketplaceUserAccountApproval>}
     * @memberof GcpMarketplaceUserAccount
     */
    'approvals'?: Array<GcpMarketplaceUserAccountApproval>;
    /**
     * The buyer\'s GCP billing account ID.
     * @type {string}
     * @memberof GcpMarketplaceUserAccount
     */
    'billingAccountId'?: string;
    /**
     * 
     * @type {CompanyInfo}
     * @memberof GcpMarketplaceUserAccount
     */
    'companyInfo'?: CompanyInfo;
    /**
     * 
     * @type {string}
     * @memberof GcpMarketplaceUserAccount
     */
    'createTime'?: string;
    /**
     * GCP Marketplace User Account ID.
     * @type {string}
     * @memberof GcpMarketplaceUserAccount
     */
    'id'?: string;
    /**
     * RFC3339 UTC timestamp
     * @type {Array<number>}
     * @memberof GcpMarketplaceUserAccount
     */
    'inputProperties'?: Array<number>;
    /**
     * The resource name of the account. Account names have the form providers/{provider_id}/accounts/{account_id}.
     * @type {string}
     * @memberof GcpMarketplaceUserAccount
     */
    'name'?: string;
    /**
     * The identifier of the service provider (SaaS Seller) that this account was created against.
     * @type {string}
     * @memberof GcpMarketplaceUserAccount
     */
    'provider'?: string;
    /**
     * The state of the account. An account might not be able to make a purchase if the billing account is suspended, for example.
     * @type {GcpMarketplaceUserAccountState}
     * @memberof GcpMarketplaceUserAccount
     */
    'state'?: GcpMarketplaceUserAccountState;
    /**
     * RFC3339 UTC timestamp
     * @type {string}
     * @memberof GcpMarketplaceUserAccount
     */
    'updateTime'?: string;
    /**
     * 
     * @type {GcpUserInfo}
     * @memberof GcpMarketplaceUserAccount
     */
    'userInfo'?: GcpUserInfo;
}

