/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @enum {string}
 */
export type GcpMarketplaceEntitlementState = 'ENTITLEMENT_STATE_UNSPECIFIED' | 'ENTITLEMENT_ACTIVATION_REQUESTED' | 'ENTITLEMENT_ACTIVE' | 'ENTITLEMENT_PENDING_CANCELLATION' | 'ENTITLEMENT_CANCELLED' | 'ENTITLEMENT_PENDING_PLAN_CHANGE' | 'ENTITLEMENT_PENDING_PLAN_CHANGE_APPROVAL' | 'ENTITLEMENT_SUSPENDED'

