/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GcpCommerceProducerPurchaseMetric } from './gcp-commerce-producer-purchase-metric';
// May contain unused imports in some cases
// @ts-ignore
import { GcpCommerceProducerServiceBilling } from './gcp-commerce-producer-service-billing';

/**
 * 
 * @export
 * @interface GcpCommerceProducerServiceConfig
 */
export interface GcpCommerceProducerServiceConfig {
    /**
     * The Product title
     * @type {string}
     * @memberof GcpCommerceProducerServiceConfig
     */
    'title'?: string;
    /**
     * 
     * @type {GcpCommerceProducerServiceBilling}
     * @memberof GcpCommerceProducerServiceConfig
     */
    'billing'?: GcpCommerceProducerServiceBilling;
    /**
     * Metrics: Defines the metrics used by this service.
     * @type {Array<GcpCommerceProducerPurchaseMetric>}
     * @memberof GcpCommerceProducerServiceConfig
     */
    'metrics'?: Array<GcpCommerceProducerPurchaseMetric>;
    /**
     * In format of \"{product-name}.endpoints.{provider-id}.cloud.goog\"
     * @type {string}
     * @memberof GcpCommerceProducerServiceConfig
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GcpCommerceProducerServiceConfig
     */
    'producerProjectId'?: string;
}

