/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GcpCommerceProducerPriceTier } from './gcp-commerce-producer-price-tier';

/**
 * 
 * @export
 * @interface GcpCommerceProducerPriceUsage
 */
export interface GcpCommerceProducerPriceUsage {
    /**
     * Default value is 1.
     * @type {number}
     * @memberof GcpCommerceProducerPriceUsage
     */
    'displayQuantity'?: number;
    /**
     * the usage metering dimension key
     * @type {string}
     * @memberof GcpCommerceProducerPriceUsage
     */
    'metricId'?: string;
    /**
     * 
     * @type {Array<GcpCommerceProducerPriceTier>}
     * @memberof GcpCommerceProducerPriceUsage
     */
    'priceTiers'?: Array<GcpCommerceProducerPriceTier>;
    /**
     * 
     * @type {string}
     * @memberof GcpCommerceProducerPriceUsage
     */
    'taxCategoryOverride'?: GcpCommerceProducerPriceUsageTaxCategoryOverrideEnum;
}

type GcpCommerceProducerPriceUsageTaxCategoryOverrideEnum = 'TAX_CATEGORY_UNSPECIFIED'


