/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GcpMarketplaceConsumer } from './gcp-marketplace-consumer';
// May contain unused imports in some cases
// @ts-ignore
import { GcpMarketplaceEntitlementState } from './gcp-marketplace-entitlement-state';

/**
 * 
 * @export
 * @interface GcpMarketplaceEntitlement
 */
export interface GcpMarketplaceEntitlement {
    /**
     * The resource name of the account that this entitlement is based on, if any, in format \"\"providers/{provider_id}/accounts/{account_id}\"
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'account'?: string;
    /**
     * The resources using this entitlement, if applicable.
     * @type {Array<GcpMarketplaceConsumer>}
     * @memberof GcpMarketplaceEntitlement
     */
    'consumers'?: Array<GcpMarketplaceConsumer>;
    /**
     * 
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'createTime'?: string;
    /**
     * Entitlement Id generated by GCP Marketplace. For Marketplace pub/sub event.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'id'?: string;
    /**
     * The custom properties that were collected from the user to create this entitlement.
     * @type {Array<number>}
     * @memberof GcpMarketplaceEntitlement
     */
    'inputProperties'?: Array<number>;
    /**
     * Provider-supplied message that is displayed to the end user. Currently this is used to communicate progress and ETA for provisioning. This field can be updated only when a user is waiting for an action from the provider, i.e. entitlement state is EntitlementState.ENTITLEMENT_ACTIVATION_REQUESTED or EntitlementState.ENTITLEMENT_PENDING_PLAN_CHANGE_APPROVAL. This field is cleared automatically when the entitlement state changes.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'messageToUser'?: string;
    /**
     * The resource name of the entitlement. Entitlement names have the form `providers/{provider_id}/entitlements/{entitlement_id}`.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'name'?: string;
    /**
     * in ISO 8601 duration format, such as \"P2Y3M\". For Marketplace pub/sub event.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'newOfferDuration'?: string;
    /**
     * Output only. The end time of the new offer. Field is empty if the pending plan change is not moving to an offer. If the offer was created with a term instead of a specified end date, this field is empty.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'newOfferEndTime'?: string;
    /**
     * Output only. The start time of the new offer. Field is empty if the pending plan change is not moving to an offer.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'newOfferStartTime'?: string;
    /**
     * The name of the offer the entitlement is switching to upon a pending plan change. Only exists if the pending plan change is moving to an offer. Format: \'projects/{project}/services/{service}/privateOffers/{offer-id}\' OR \'projects/{project}/services/{service}/standardOffers/{offer-id}\', depending on whether the offer is private or public.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'newPendingOffer'?: string;
    /**
     * The offer duration of the new offer in ISO 8601 duration format. Field is empty if the pending plan change is not moving to an offer since the entitlement is not pending, only the plan change is pending.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'newPendingOfferDuration'?: string;
    /**
     * The identifier of the pending new plan. Required if the product has plans and the entitlement has a pending plan change.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'newPendingPlan'?: string;
    /**
     * When the buyer changes plan, For Marketplace pub/sub event.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'newPlan'?: string;
    /**
     * The name of the offer that was procured. Field is empty if order was not made using an offer. Format: \'projects/{project}/services/{service}/privateOffers/{offer-id}\' OR \'projects/{project}/services/{service}/standardOffers/{offer-id}\', depending on whether the offer is private or public.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'offer'?: string;
    /**
     * The offer duration of the current offer in ISO 8601 duration format. Field is empty if entitlement was not made using an offer, such as \"P1Y\", \"P2M\"
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'offerDuration'?: string;
    /**
     * Output only. End time for the Offer association corresponding to this entitlement. The field is only populated if the entitlement is currently associated with an Offer.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'offerEndTime'?: string;
    /**
     * The identifier of the plan that was procured. Required if the product has plans.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'plan'?: string;
    /**
     * The identifier of the entity that was purchased. This may actually represent a product, quote, or offer. For Private offer, \"projects/project-id/services/product-id.endpoints.partner-id.cloud.goog/privateOffers/private-offer-id\"
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'product'?: string;
    /**
     * The identifier of the product that was procured.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'productExternalName'?: string;
    /**
     * The ID of the service provider under Cloud Commerce platform that this entitlement was created against.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'provider'?: string;
    /**
     * The identifier of the quote that was used to procure, such as the private offer Id. Empty if the order is not purchased using a quote.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'quoteExternalName'?: string;
    /**
     * Enums of the Entitlement State. https://cloud.google.com/marketplace/docs/partners/commerce-procurement-api/reference/rest/v1/providers.entitlements#EntitlementState
     * @type {GcpMarketplaceEntitlementState}
     * @memberof GcpMarketplaceEntitlement
     */
    'state'?: GcpMarketplaceEntitlementState;
    /**
     * The End time for the subscription corresponding to this entitlement.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'subscriptionEndTime'?: string;
    /**
     * The last update timestamp. It is the endTime for the cancelled entitlement.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'updateTime'?: string;
    /**
     * The consumerId to use when reporting usage through the Service Control API. See the consumerId field at Reporting Metrics (https://cloud.google.com/service-control/reporting-metrics) for more details. This field is present only if the product has usage-based billing configured.
     * @type {string}
     * @memberof GcpMarketplaceEntitlement
     */
    'usageReportingId'?: string;
}

