/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GcpCommerceProducerListingSpec } from './gcp-commerce-producer-listing-spec';
// May contain unused imports in some cases
// @ts-ignore
import { GcpCommerceProducerServiceConfig } from './gcp-commerce-producer-service-config';

/**
 * 
 * @export
 * @interface GcpProduct
 */
export interface GcpProduct {
    /**
     * 
     * @type {string}
     * @memberof GcpProduct
     */
    'createTime'?: string;
    /**
     * Nullable, GCP Marketplace Product UUID
     * @type {string}
     * @memberof GcpProduct
     */
    'id'?: string;
    /**
     * 
     * @type {GcpCommerceProducerListingSpec}
     * @memberof GcpProduct
     */
    'listingSpec'?: GcpCommerceProducerListingSpec;
    /**
     * 
     * @type {string}
     * @memberof GcpProduct
     */
    'marketplace'?: GcpProductMarketplaceEnum;
    /**
     * In format of \"projects/{project-number}/listings/{product-name}.endpoints.{provider-id}.cloud.goog\"
     * @type {string}
     * @memberof GcpProduct
     */
    'name'?: string;
    /**
     * In format of \"services/{product-name}.endpoints.{provider-id}.cloud.goog\"
     * @type {string}
     * @memberof GcpProduct
     */
    'service'?: string;
    /**
     * 
     * @type {GcpCommerceProducerServiceConfig}
     * @memberof GcpProduct
     */
    'serviceConfig'?: GcpCommerceProducerServiceConfig;
}

type GcpProductMarketplaceEnum = 'marketplaces/google-cloud'


