/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GcpCommerceProducerPrice } from './gcp-commerce-producer-price';

/**
 * The price of this tier
 * @export
 * @interface GcpCommerceProducerPriceTierPrice
 */
export interface GcpCommerceProducerPriceTierPrice {
    /**
     * ISO currency code, Three UPPER_CASE characters
     * @type {string}
     * @memberof GcpCommerceProducerPriceTierPrice
     */
    'currencyCode'?: string;
    /**
     * Decimal part of the price. For example, 2000000 = 0.002, 200000000 = 0.2
     * @type {number}
     * @memberof GcpCommerceProducerPriceTierPrice
     */
    'nanos'?: number;
    /**
     * Integer part of the price.
     * @type {number}
     * @memberof GcpCommerceProducerPriceTierPrice
     */
    'units'?: number;
}

