/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GcpCommerceProducerSupportSpec } from './gcp-commerce-producer-support-spec';

/**
 * 
 * @export
 * @interface GcpCommerceProducerMarketingSpec
 */
export interface GcpCommerceProducerMarketingSpec {
    /**
     * The product title.
     * @type {string}
     * @memberof GcpCommerceProducerMarketingSpec
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof GcpCommerceProducerMarketingSpec
     */
    'description'?: string;
    /**
     * In format of \"{provider-id}/{product-name}\"
     * @type {Array<string>}
     * @memberof GcpCommerceProducerMarketingSpec
     */
    'displayNames'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GcpCommerceProducerMarketingSpec
     */
    'eulaUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof GcpCommerceProducerMarketingSpec
     */
    'externalMarketingUrl'?: string;
    /**
     * In format of \"base64://...\"
     * @type {string}
     * @memberof GcpCommerceProducerMarketingSpec
     */
    'icon'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GcpCommerceProducerMarketingSpec
     */
    'searchCategories'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GcpCommerceProducerMarketingSpec
     */
    'searchDescription'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GcpCommerceProducerMarketingSpec
     */
    'searchKeywords'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GcpCommerceProducerMarketingSpec
     */
    'shortTitle'?: string;
    /**
     * 
     * @type {GcpCommerceProducerSupportSpec}
     * @memberof GcpCommerceProducerMarketingSpec
     */
    'supportSpec'?: GcpCommerceProducerSupportSpec;
}

