/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GcpMarketplaceUserAccountApprovalState } from './gcp-marketplace-user-account-approval-state';

/**
 * 
 * @export
 * @interface GcpMarketplaceUserAccountApproval
 */
export interface GcpMarketplaceUserAccountApproval {
    /**
     * 
     * @type {string}
     * @memberof GcpMarketplaceUserAccountApproval
     */
    'name'?: string;
    /**
     * An explanation for the state of the approval.
     * @type {string}
     * @memberof GcpMarketplaceUserAccountApproval
     */
    'reason'?: string;
    /**
     * 
     * @type {GcpMarketplaceUserAccountApprovalState}
     * @memberof GcpMarketplaceUserAccountApproval
     */
    'state'?: GcpMarketplaceUserAccountApprovalState;
    /**
     * RFC3339 UTC timestamp
     * @type {string}
     * @memberof GcpMarketplaceUserAccountApproval
     */
    'updateTime'?: string;
}

