/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface GcpUserInfo
 */
export interface GcpUserInfo {
    /**
     * An array of strings representing the user\'s roles. Right now, it can be either: ** account_admin, which indicates that the user is a Billing Account Administrator of the billing account that purchased the product, or ** project_editor, which indicates that the user is a Project Editor, but not a Billing Administrator, of the project under that billing account.
     * @type {Array<string>}
     * @memberof GcpUserInfo
     */
    'roles'?: Array<string>;
    /**
     * The user\'s obfuscated GAIA ID, which can be used to initiate Open ID Connect.
     * @type {string}
     * @memberof GcpUserInfo
     */
    'user_identity'?: string;
}

