/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GcpCommerceProducerPriceModel } from './gcp-commerce-producer-price-model';
// May contain unused imports in some cases
// @ts-ignore
import { GcpCommerceProducerPriceSubscription } from './gcp-commerce-producer-price-subscription';
// May contain unused imports in some cases
// @ts-ignore
import { GcpCommerceProducerPriceUsage } from './gcp-commerce-producer-price-usage';

/**
 * 
 * @export
 * @interface GcpCommerceProducerPriceInfo
 */
export interface GcpCommerceProducerPriceInfo {
    /**
     * 
     * @type {string}
     * @memberof GcpCommerceProducerPriceInfo
     */
    'description'?: string;
    /**
     * 
     * @type {GcpCommerceProducerPriceModel}
     * @memberof GcpCommerceProducerPriceInfo
     */
    'priceModel'?: GcpCommerceProducerPriceModel;
    /**
     * Commit price plan, when priceModel = SUBSCRIPTION or SUBSCRIPTION_PLUS_USAGE.
     * @type {Array<GcpCommerceProducerPriceSubscription>}
     * @memberof GcpCommerceProducerPriceInfo
     */
    'subscriptionPlans'?: Array<GcpCommerceProducerPriceSubscription>;
    /**
     * Usage based metering plan, when priceModel =  USAGE or SUBSCRIPTION_PLUS_USAGE
     * @type {Array<GcpCommerceProducerPriceUsage>}
     * @memberof GcpCommerceProducerPriceInfo
     */
    'usageFees'?: Array<GcpCommerceProducerPriceUsage>;
}

