/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface GithubComAwsAwsSdkGoV2ServiceMarketplacemeteringTypesTag
 */
export interface GithubComAwsAwsSdkGoV2ServiceMarketplacemeteringTypesTag {
    /**
     * One part of a key-value pair that makes up a tag. A key is a label that acts like a category for the specific tag values.  This member is required.
     * @type {string}
     * @memberof GithubComAwsAwsSdkGoV2ServiceMarketplacemeteringTypesTag
     */
    'key'?: string;
    /**
     * One part of a key-value pair that makes up a tag. A value acts as a descriptor within a tag category (key). The value can be empty or null.  This member is required.
     * @type {string}
     * @memberof GithubComAwsAwsSdkGoV2ServiceMarketplacemeteringTypesTag
     */
    'value'?: string;
}

