/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
 */
export interface GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue {
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'azureAssetID'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'azureBillingAccountID'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'azureCustomerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'azureOfferID'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'azurePlanID'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'billingModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'buyerID'?: string;
    /**
     * 
     * @type {number}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'earningUsd'?: number;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'entitlementID'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'offerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'organizationID'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'payoutStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'productID'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'purchaseRecordID'?: string;
    /**
     * 
     * @type {number}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'revenueUsd'?: number;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'termEndDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue
     */
    'termStartDate'?: string;
}

