/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageEventConflictResponse } from './github-com-sugerio-marketplace-service-azure-sdk-marketplacemeteringv1-usage-event-conflict-response';
// May contain unused imports in some cases
// @ts-ignore
import { GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageEventStatusEnum } from './github-com-sugerio-marketplace-service-azure-sdk-marketplacemeteringv1-usage-event-status-enum';

/**
 * 
 * @export
 * @interface GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageBatchEventOkMessage
 */
export interface GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageBatchEventOkMessage {
    /**
     * Dimension identifier
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageBatchEventOkMessage
     */
    'dimension'?: string;
    /**
     * Time in UTC when the usage event occurred
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageBatchEventOkMessage
     */
    'effectiveStartTime'?: string;
    /**
     * 
     * @type {GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageEventConflictResponse}
     * @memberof GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageBatchEventOkMessage
     */
    'error'?: GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageEventConflictResponse;
    /**
     * Time this message was created in UTC
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageBatchEventOkMessage
     */
    'messageTime'?: string;
    /**
     * Plan associated with the purchased offer
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageBatchEventOkMessage
     */
    'planId'?: string;
    /**
     * Number of units consumed
     * @type {number}
     * @memberof GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageBatchEventOkMessage
     */
    'quantity'?: number;
    /**
     * Identifier of the resource against which usage is emitted
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageBatchEventOkMessage
     */
    'resourceId'?: string;
    /**
     * Identifier of the managed app resource against which usage is emitted
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageBatchEventOkMessage
     */
    'resourceUri'?: string;
    /**
     * Status of the operation.
     * @type {GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageEventStatusEnum}
     * @memberof GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageBatchEventOkMessage
     */
    'status'?: GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageEventStatusEnum;
    /**
     * Unique identifier associated with the usage event
     * @type {string}
     * @memberof GithubComSugerioMarketplaceServiceAzureSdkMarketplacemeteringv1UsageBatchEventOkMessage
     */
    'usageEventId'?: string;
}

