/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface HubspotCrmCredential
 */
export interface HubspotCrmCredential {
    /**
     * 
     * @type {string}
     * @memberof HubspotCrmCredential
     */
    'accessToken'?: string;
    /**
     * UTC timestamp on receiving the auth response
     * @type {number}
     * @memberof HubspotCrmCredential
     */
    'acquiredOn'?: number;
    /**
     * 
     * @type {number}
     * @memberof HubspotCrmCredential
     */
    'expiresIn'?: number;
    /**
     * 
     * @type {string}
     * @memberof HubspotCrmCredential
     */
    'refreshToken'?: string;
}

