/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BuyerInfo } from './buyer-info';

/**
 * 
 * @export
 * @interface IdentityBuyer
 */
export interface IdentityBuyer {
    /**
     * 
     * @type {BuyerInfo}
     * @memberof IdentityBuyer
     */
    'info'?: BuyerInfo;
    /**
     * 
     * @type {string}
     * @memberof IdentityBuyer
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityBuyer
     */
    'creationTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityBuyer
     */
    'externalID'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityBuyer
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityBuyer
     */
    'lastUpdateTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityBuyer
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityBuyer
     */
    'organizationID'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityBuyer
     */
    'partner'?: IdentityBuyerPartnerEnum;
}

type IdentityBuyerPartnerEnum = 'AWS' | 'AZURE' | 'GCP'


