/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { IntegrationInfo } from './integration-info';

/**
 * 
 * @export
 * @interface IdentityIntegration
 */
export interface IdentityIntegration {
    /**
     * 
     * @type {IntegrationInfo}
     * @memberof IdentityIntegration
     */
    'info'?: IntegrationInfo;
    /**
     * 
     * @type {string}
     * @memberof IdentityIntegration
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityIntegration
     */
    'creationTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityIntegration
     */
    'lastUpdateTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityIntegration
     */
    'lastUpdatedBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityIntegration
     */
    'organizationID'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityIntegration
     */
    'partner'?: IdentityIntegrationPartnerEnum;
    /**
     * 
     * @type {string}
     * @memberof IdentityIntegration
     */
    'service'?: IdentityIntegrationServiceEnum;
    /**
     * 
     * @type {string}
     * @memberof IdentityIntegration
     */
    'status'?: IdentityIntegrationStatusEnum;
}

type IdentityIntegrationPartnerEnum = 'AWS' | 'AZURE' | 'GCP'
type IdentityIntegrationServiceEnum = 'MARKETPLACE'
type IdentityIntegrationStatusEnum = 'CREATED' | 'VERIFIED' | 'NOT_VERIFIED'


