/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { IntegrationInfoAwsAceIntegration } from './integration-info-aws-ace-integration';
// May contain unused imports in some cases
// @ts-ignore
import { IntegrationInfoAwsIntegration } from './integration-info-aws-integration';
// May contain unused imports in some cases
// @ts-ignore
import { IntegrationInfoAzureIntegration } from './integration-info-azure-integration';
// May contain unused imports in some cases
// @ts-ignore
import { IntegrationInfoGcpIntegration } from './integration-info-gcp-integration';
// May contain unused imports in some cases
// @ts-ignore
import { IntegrationInfoHubspotCrmIntegration } from './integration-info-hubspot-crm-integration';
// May contain unused imports in some cases
// @ts-ignore
import { IntegrationInfoSalesforceCrmIntegration } from './integration-info-salesforce-crm-integration';
// May contain unused imports in some cases
// @ts-ignore
import { SlackIntegration } from './slack-integration';

/**
 * 
 * @export
 * @interface IntegrationInfo
 */
export interface IntegrationInfo {
    /**
     * 
     * @type {IntegrationInfoAwsAceIntegration}
     * @memberof IntegrationInfo
     */
    'awsAceIntegration'?: IntegrationInfoAwsAceIntegration;
    /**
     * 
     * @type {IntegrationInfoAwsIntegration}
     * @memberof IntegrationInfo
     */
    'awsIntegration'?: IntegrationInfoAwsIntegration;
    /**
     * 
     * @type {IntegrationInfoAzureIntegration}
     * @memberof IntegrationInfo
     */
    'azureIntegration'?: IntegrationInfoAzureIntegration;
    /**
     * 
     * @type {IntegrationInfoGcpIntegration}
     * @memberof IntegrationInfo
     */
    'gcpIntegration'?: IntegrationInfoGcpIntegration;
    /**
     * 
     * @type {IntegrationInfoHubspotCrmIntegration}
     * @memberof IntegrationInfo
     */
    'hubspotCrmIntegration'?: IntegrationInfoHubspotCrmIntegration;
    /**
     * 
     * @type {IntegrationInfoSalesforceCrmIntegration}
     * @memberof IntegrationInfo
     */
    'salesforceCrmIntegration'?: IntegrationInfoSalesforceCrmIntegration;
    /**
     * 
     * @type {SlackIntegration}
     * @memberof IntegrationInfo
     */
    'slackIntegration'?: SlackIntegration;
}

