/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { HubspotCrmCredential } from './hubspot-crm-credential';
// May contain unused imports in some cases
// @ts-ignore
import { HubspotCrmIntegration } from './hubspot-crm-integration';

/**
 * Integration for HubSpot CRM
 * @export
 * @interface IntegrationInfoHubspotCrmIntegration
 */
export interface IntegrationInfoHubspotCrmIntegration {
    /**
     * 
     * @type {HubspotCrmCredential}
     * @memberof IntegrationInfoHubspotCrmIntegration
     */
    'credential'?: HubspotCrmCredential;
    /**
     * Hubspot Account Id
     * @type {number}
     * @memberof IntegrationInfoHubspotCrmIntegration
     */
    'portalId'?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationInfoHubspotCrmIntegration
     */
    'secretKey'?: string;
}

