/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { UsageMeteringDailyVerification } from './usage-metering-daily-verification';

/**
 * 
 * @export
 * @interface ListUsageMeteringDailyVerificationsResponse
 */
export interface ListUsageMeteringDailyVerificationsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListUsageMeteringDailyVerificationsResponse
     */
    'nextOffset'?: number;
    /**
     * per day per dimension.
     * @type {Array<UsageMeteringDailyVerification>}
     * @memberof ListUsageMeteringDailyVerificationsResponse
     */
    'usageMeteringDailyVerifications'?: Array<UsageMeteringDailyVerification>;
}

