/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MeteringUsageRecordGroup } from './metering-usage-record-group';

/**
 * 
 * @export
 * @interface ListUsageRecordGroupsResponse
 */
export interface ListUsageRecordGroupsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListUsageRecordGroupsResponse
     */
    'nextOffset'?: number;
    /**
     * 
     * @type {Array<MeteringUsageRecordGroup>}
     * @memberof ListUsageRecordGroupsResponse
     */
    'usageRecordGroups'?: Array<MeteringUsageRecordGroup>;
}

