/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MeteringUsageRecordReportInfo } from './metering-usage-record-report-info';

/**
 * 
 * @export
 * @interface MeteringUsageRecordReport
 */
export interface MeteringUsageRecordReport {
    /**
     * 
     * @type {MeteringUsageRecordReportInfo}
     * @memberof MeteringUsageRecordReport
     */
    'info'?: MeteringUsageRecordReportInfo;
    /**
     * 
     * @type {string}
     * @memberof MeteringUsageRecordReport
     */
    'buyerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringUsageRecordReport
     */
    'creationTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringUsageRecordReport
     */
    'entitlementID'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringUsageRecordReport
     */
    'entitlementTermID'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringUsageRecordReport
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringUsageRecordReport
     */
    'organizationID'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringUsageRecordReport
     */
    'partner'?: MeteringUsageRecordReportPartnerEnum;
    /**
     * 
     * @type {string}
     * @memberof MeteringUsageRecordReport
     */
    'productID'?: string;
}

type MeteringUsageRecordReportPartnerEnum = 'AWS' | 'AZURE' | 'GCP'


