/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MarketplacemeteringBatchMeterUsageOutput } from './marketplacemetering-batch-meter-usage-output';
// May contain unused imports in some cases
// @ts-ignore
import { TypesUsageRecord } from './types-usage-record';
// May contain unused imports in some cases
// @ts-ignore
import { TypesUsageRecordResult } from './types-usage-record-result';

/**
 * The raw response from AWS metering service.
 * @export
 * @interface MeteringUsageRecordReportInfoAwsMeteringResponse
 */
export interface MeteringUsageRecordReportInfoAwsMeteringResponse {
    /**
     * Metadata pertaining to the operation\'s result.
     * @type {object}
     * @memberof MeteringUsageRecordReportInfoAwsMeteringResponse
     */
    'resultMetadata'?: object;
    /**
     * Contains all UsageRecords processed by BatchMeterUsage. These records were either honored by AWS Marketplace Metering Service or were invalid. Invalid records should be fixed before being resubmitted.
     * @type {Array<TypesUsageRecordResult>}
     * @memberof MeteringUsageRecordReportInfoAwsMeteringResponse
     */
    'results'?: Array<TypesUsageRecordResult>;
    /**
     * Contains all UsageRecords that were not processed by BatchMeterUsage. This is a list of UsageRecords. You can retry the failed request by making another BatchMeterUsage call with this list as input in the BatchMeterUsageRequest.
     * @type {Array<TypesUsageRecord>}
     * @memberof MeteringUsageRecordReportInfoAwsMeteringResponse
     */
    'unprocessedRecords'?: Array<TypesUsageRecord>;
}

