/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface MeteringUsageRecordGroupMetaInfo
 */
export interface MeteringUsageRecordGroupMetaInfo {
    /**
     * The original records reported by the customer before convertion. If no dimension mapping is applied, this field is the same as the records field.
     * @type {{ [key: string]: number; }}
     * @memberof MeteringUsageRecordGroupMetaInfo
     */
    'originRecords'?: { [key: string]: number; };
}

