/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MeteringUsageRecordReportInfoAwsMeteringResponse } from './metering-usage-record-report-info-aws-metering-response';
// May contain unused imports in some cases
// @ts-ignore
import { MeteringUsageRecordReportInfoAzureMeteringResponse } from './metering-usage-record-report-info-azure-metering-response';
// May contain unused imports in some cases
// @ts-ignore
import { MeteringUsageRecordReportInfoGcpMeteringResponse } from './metering-usage-record-report-info-gcp-metering-response';

/**
 * 
 * @export
 * @interface MeteringUsageRecordReportInfo
 */
export interface MeteringUsageRecordReportInfo {
    /**
     * 
     * @type {MeteringUsageRecordReportInfoAwsMeteringResponse}
     * @memberof MeteringUsageRecordReportInfo
     */
    'awsMeteringResponse'?: MeteringUsageRecordReportInfoAwsMeteringResponse;
    /**
     * 
     * @type {MeteringUsageRecordReportInfoAzureMeteringResponse}
     * @memberof MeteringUsageRecordReportInfo
     */
    'azureMeteringResponse'?: MeteringUsageRecordReportInfoAzureMeteringResponse;
    /**
     * The amount of the commit if applicable.
     * @type {number}
     * @memberof MeteringUsageRecordReportInfo
     */
    'commitAmount'?: number;
    /**
     * The amount of the credit if applicable.
     * @type {number}
     * @memberof MeteringUsageRecordReportInfo
     */
    'creditAmount'?: number;
    /**
     * The credit usage records in the map of <DimensionKey, Count>
     * @type {{ [key: string]: number; }}
     * @memberof MeteringUsageRecordReportInfo
     */
    'creditRecords'?: { [key: string]: number; };
    /**
     * The decimal parts of the usage dimension quantity in the map of <DimensionKey, DecimalPart>, before this usage record report.
     * @type {{ [key: string]: number; }}
     * @memberof MeteringUsageRecordReportInfo
     */
    'decimalParts'?: { [key: string]: number; };
    /**
     * The public list price of each dimension in the map of <DimensionKey, UnitPrice>.
     * @type {{ [key: string]: number; }}
     * @memberof MeteringUsageRecordReportInfo
     */
    'dimensionUnitListPrice'?: { [key: string]: number; };
    /**
     * The unit price of each dimension in the map of <DimensionKey, UnitPrice>. It can be the negotiated price in the private offer or the public list price.
     * @type {{ [key: string]: number; }}
     * @memberof MeteringUsageRecordReportInfo
     */
    'dimensionUnitPrice'?: { [key: string]: number; };
    /**
     * time in UTC when the UsageRecordReport ends
     * @type {string}
     * @memberof MeteringUsageRecordReportInfo
     */
    'endTime'?: string;
    /**
     * 
     * @type {MeteringUsageRecordReportInfoGcpMeteringResponse}
     * @memberof MeteringUsageRecordReportInfo
     */
    'gcpMeteringResponse'?: MeteringUsageRecordReportInfoGcpMeteringResponse;
    /**
     * The included usage records in the map of <DimensionKey, Count>
     * @type {{ [key: string]: number; }}
     * @memberof MeteringUsageRecordReportInfo
     */
    'includedRecords'?: { [key: string]: number; };
    /**
     * The decimal parts of the usage dimension quantity in the map of <DimensionKey, DecimalPart>, after this usage record report.
     * @type {{ [key: string]: number; }}
     * @memberof MeteringUsageRecordReportInfo
     */
    'newDecimalParts'?: { [key: string]: number; };
    /**
     * The partner where this usage record report is sent to. Such as AWS, AZURE or GCP.
     * @type {string}
     * @memberof MeteringUsageRecordReportInfo
     */
    'partner'?: string;
    /**
     * The usage records to report before the adjustment by the commit with additional usage at list price, in the map of <DimensionKey, Count>.
     * @type {{ [key: string]: number; }}
     * @memberof MeteringUsageRecordReportInfo
     */
    'recordsToReportBeforeAdjustmentAtListPrice'?: { [key: string]: number; };
    /**
     * The reported usage records in the map of <DimensionKey, Count>
     * @type {{ [key: string]: number; }}
     * @memberof MeteringUsageRecordReportInfo
     */
    'reportedRecords'?: { [key: string]: number; };
    /**
     * time in UTC when the UsageRecordReport starts
     * @type {string}
     * @memberof MeteringUsageRecordReportInfo
     */
    'startTime'?: string;
    /**
     * The IDs of UsageRecordGroups aggregated in this UsageRecordReport.
     * @type {Array<string>}
     * @memberof MeteringUsageRecordReportInfo
     */
    'usageRecordGroupIds'?: Array<string>;
    /**
     * The amount of the used commit before this usage record report if applicable.
     * @type {number}
     * @memberof MeteringUsageRecordReportInfo
     */
    'usedCommitAmount'?: number;
    /**
     * The amount of the used commit increment in this usage record report if applicable.
     * @type {number}
     * @memberof MeteringUsageRecordReportInfo
     */
    'usedCommitAmountIncrement'?: number;
    /**
     * The amount of the used credit before this usage record report if applicable.
     * @type {number}
     * @memberof MeteringUsageRecordReportInfo
     */
    'usedCreditAmount'?: number;
    /**
     * The amount of the used credit increment in this usage record report if applicable.
     * @type {number}
     * @memberof MeteringUsageRecordReportInfo
     */
    'usedCreditAmountIncrement'?: number;
}

