/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { UsageCount } from './usage-count';

/**
 * The current Dimension Usage Count. Available when call GetEntitlement API.
 * @export
 * @interface MeteringDimensionUsageCount
 */
export interface MeteringDimensionUsageCount {
    /**
     * The count of this dimension usage records that are handled as credit.
     * @type {number}
     * @memberof MeteringDimensionUsageCount
     */
    'creditCount'?: number;
    /**
     * The count of this dimension usage records that are handled as included in IncludedBaseQuantity
     * @type {number}
     * @memberof MeteringDimensionUsageCount
     */
    'includedCount'?: number;
    /**
     * The count of this dimension usage records that are reported to cloud vendors.
     * @type {number}
     * @memberof MeteringDimensionUsageCount
     */
    'reportedCount'?: number;
}

