/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AzureAudience } from './azure-audience';
// May contain unused imports in some cases
// @ts-ignore
import { AzureProductVariant } from './azure-product-variant';
// May contain unused imports in some cases
// @ts-ignore
import { CommitDimension } from './commit-dimension';
// May contain unused imports in some cases
// @ts-ignore
import { EulaType } from './eula-type';
// May contain unused imports in some cases
// @ts-ignore
import { GcpCommerceProducerPurchaseMetric } from './gcp-commerce-producer-purchase-metric';
// May contain unused imports in some cases
// @ts-ignore
import { GcpPurchasePlan } from './gcp-purchase-plan';
// May contain unused imports in some cases
// @ts-ignore
import { MeteringDimension } from './metering-dimension';
// May contain unused imports in some cases
// @ts-ignore
import { OfferInfoAzureOriginalPlan } from './offer-info-azure-original-plan';
// May contain unused imports in some cases
// @ts-ignore
import { OfferInfoAzurePrivateOffer } from './offer-info-azure-private-offer';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentInstallment } from './payment-installment';

/**
 * 
 * @export
 * @interface OfferInfo
 */
export interface OfferInfo {
    /**
     * 
     * @type {OfferInfoAzureOriginalPlan}
     * @memberof OfferInfo
     */
    'azureOriginalPlan'?: OfferInfoAzureOriginalPlan;
    /**
     * 
     * @type {OfferInfoAzurePrivateOffer}
     * @memberof OfferInfo
     */
    'azurePrivateOffer'?: OfferInfoAzurePrivateOffer;
    /**
     * 
     * @type {AzureProductVariant}
     * @memberof OfferInfo
     */
    'azureProductVariant'?: AzureProductVariant;
    /**
     * The buyers\' AWS Account IDs of this offer.
     * @type {Array<string>}
     * @memberof OfferInfo
     */
    'buyerAwsAccountIds'?: Array<string>;
    /**
     * The buyers\' Azure tenants of this offer.
     * @type {Array<AzureAudience>}
     * @memberof OfferInfo
     */
    'buyerAzureTenants'?: Array<AzureAudience>;
    /**
     * 
     * @type {Array<CommitDimension>}
     * @memberof OfferInfo
     */
    'commits'?: Array<CommitDimension>;
    /**
     * 
     * @type {string}
     * @memberof OfferInfo
     */
    'currency'?: string;
    /**
     * 
     * @type {Array<MeteringDimension>}
     * @memberof OfferInfo
     */
    'dimensions'?: Array<MeteringDimension>;
    /**
     * The rate of discount (0 ~ 1.0), such as 0.1 which is 10% off. 0 which is no discount.
     * @type {number}
     * @memberof OfferInfo
     */
    'discount'?: number;
    /**
     * 
     * @type {EulaType}
     * @memberof OfferInfo
     */
    'eulaType'?: EulaType;
    /**
     * 
     * @type {string}
     * @memberof OfferInfo
     */
    'eulaUrl'?: string;
    /**
     * Only applicable for GCP Marketplace Offers (the default or private offer)
     * @type {Array<GcpCommerceProducerPurchaseMetric>}
     * @memberof OfferInfo
     */
    'gcpMetrics'?: Array<GcpCommerceProducerPurchaseMetric>;
    /**
     * Only applicable for GCP Marketplace Offers (the default or private offer).
     * @type {Array<GcpPurchasePlan>}
     * @memberof OfferInfo
     */
    'gcpPlans'?: Array<GcpPurchasePlan>;
    /**
     * For flexible payment schedule. Not empty if it is enabled.
     * @type {Array<PaymentInstallment>}
     * @memberof OfferInfo
     */
    'paymentInstallments'?: Array<PaymentInstallment>;
    /**
     * The URL of the private offer sent to buyers to accept. Only applicable for private offer.
     * @type {string}
     * @memberof OfferInfo
     */
    'privateOfferUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferInfo
     */
    'refundCancelationPolicy'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfferInfo
     */
    'sellerNotes'?: string;
    /**
     * The default visibility of offer is PRIVATE.
     * @type {string}
     * @memberof OfferInfo
     */
    'visibility'?: OfferInfoVisibilityEnum;
}

type OfferInfoVisibilityEnum = 'PRIVATE' | 'PUBLIC'


