/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { OperationType } from './operation-type';

/**
 * 
 * @export
 * @interface Operation
 */
export interface Operation {
    /**
     * 
     * @type {string}
     * @memberof Operation
     */
    'endTime'?: string;
    /**
     * Operation ID.
     * @type {string}
     * @memberof Operation
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Operation
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof Operation
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Operation
     */
    'startTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof Operation
     */
    'status'?: string;
    /**
     * 
     * @type {OperationType}
     * @memberof Operation
     */
    'type'?: OperationType;
}

