/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Partner } from './partner';
// May contain unused imports in some cases
// @ts-ignore
import { UsageMeteringDimensionMappingValue } from './usage-metering-dimension-mapping-value';

/**
 * 
 * @export
 * @interface PartnerUsageMeteringConfig
 */
export interface PartnerUsageMeteringConfig {
    /**
     * The mapping of the source dimension key to the destination dimension key of the usage metering.
     * @type {{ [key: string]: UsageMeteringDimensionMappingValue; }}
     * @memberof PartnerUsageMeteringConfig
     */
    'dimensionMapping'?: { [key: string]: UsageMeteringDimensionMappingValue; };
    /**
     * Enable the commit (discount) with additional usage metering at list price. Only applicable if EnableCommitWithAdditionalUsageMetering is true. The default is false, which means the commit with additional usage metering at the discounted price in the private offer. If set to true, the commit with additional usage metering at the list price (the price in the public product listing) instead of the discounted price.
     * @type {boolean}
     * @memberof PartnerUsageMeteringConfig
     */
    'enableCommitWithAdditionalUsageAtListPrice'?: boolean;
    /**
     * Enable the commit with additional usage metering. The default is false, which means all usage records are reported to partner no matter how much is the commit. If set to true, the usage records will be reported to partner only if the current commit has been exhausted.
     * @type {boolean}
     * @memberof PartnerUsageMeteringConfig
     */
    'enableCommitWithAdditionalUsageMetering'?: boolean;
    /**
     * Enable the dimension mapping for the usage metering. The default is false, which means no dimension conversion and just use the origin dimension.
     * @type {boolean}
     * @memberof PartnerUsageMeteringConfig
     */
    'enableDimensionMapping'?: boolean;
    /**
     * The partner in this dimension mapping. Required. Such as AWS, AZURE or GCP.
     * @type {Partner}
     * @memberof PartnerUsageMeteringConfig
     */
    'partner'?: Partner;
}

