/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { RevenueRecordDetailAwsRevenueRecordDetail } from './revenue-record-detail-aws-revenue-record-detail';
// May contain unused imports in some cases
// @ts-ignore
import { RevenueRecordDetailAzureRevenueRecordDetail } from './revenue-record-detail-azure-revenue-record-detail';
// May contain unused imports in some cases
// @ts-ignore
import { RevenueRecordDetailGcpRevenueRecordDetail } from './revenue-record-detail-gcp-revenue-record-detail';

/**
 * 
 * @export
 * @interface RevenueRecordDetail
 */
export interface RevenueRecordDetail {
    /**
     * 
     * @type {RevenueRecordDetailAwsRevenueRecordDetail}
     * @memberof RevenueRecordDetail
     */
    'awsRevenueRecordDetail'?: RevenueRecordDetailAwsRevenueRecordDetail;
    /**
     * 
     * @type {RevenueRecordDetailAzureRevenueRecordDetail}
     * @memberof RevenueRecordDetail
     */
    'azureRevenueRecordDetail'?: RevenueRecordDetailAzureRevenueRecordDetail;
    /**
     * 
     * @type {RevenueRecordDetailGcpRevenueRecordDetail}
     * @memberof RevenueRecordDetail
     */
    'gcpRevenueRecordDetail'?: RevenueRecordDetailGcpRevenueRecordDetail;
}

