/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GithubComSugerioMarketplaceServiceRdsDbLibBillingAwsBillingEvent } from './github-com-sugerio-marketplace-service-rds-db-lib-billing-aws-billing-event';
// May contain unused imports in some cases
// @ts-ignore
import { GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue } from './github-com-sugerio-marketplace-service-rds-db-lib-billing-azure-cma-revenue';
// May contain unused imports in some cases
// @ts-ignore
import { GithubComSugerioMarketplaceServiceRdsDbLibBillingGcpChargeUsage } from './github-com-sugerio-marketplace-service-rds-db-lib-billing-gcp-charge-usage';

/**
 * 
 * @export
 * @interface RevenueRecordInfo
 */
export interface RevenueRecordInfo {
    /**
     * For raw revenue records in AWS Marketplace
     * @type {Array<GithubComSugerioMarketplaceServiceRdsDbLibBillingAwsBillingEvent>}
     * @memberof RevenueRecordInfo
     */
    'awsRevenueRecords'?: Array<GithubComSugerioMarketplaceServiceRdsDbLibBillingAwsBillingEvent>;
    /**
     * For raw revenue records in Azure Marketplace
     * @type {Array<GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue>}
     * @memberof RevenueRecordInfo
     */
    'azureRevenueRecords'?: Array<GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue>;
    /**
     * For raw revenue records in GCP Marketplace
     * @type {Array<GithubComSugerioMarketplaceServiceRdsDbLibBillingGcpChargeUsage>}
     * @memberof RevenueRecordInfo
     */
    'gcpRevenueRecords'?: Array<GithubComSugerioMarketplaceServiceRdsDbLibBillingGcpChargeUsage>;
}

