/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GithubComSugerioMarketplaceServiceRdsDbLibBillingAzureCmaRevenue } from './github-com-sugerio-marketplace-service-rds-db-lib-billing-azure-cma-revenue';

/**
 * For Azure Marketplace
 * @export
 * @interface RevenueRecordDetailAzureRevenueRecordDetail
 */
export interface RevenueRecordDetailAzureRevenueRecordDetail {
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'azureAssetID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'azureBillingAccountID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'azureCustomerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'azureOfferID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'azurePlanID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'billingModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'buyerID'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'earningUsd'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'entitlementID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'offerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'organizationID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'payoutStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'productID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'purchaseRecordID'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'revenueUsd'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'termEndDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAzureRevenueRecordDetail
     */
    'termStartDate'?: string;
}

