/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GithubComSugerioMarketplaceServiceRdsDbLibBillingAwsBillingEvent } from './github-com-sugerio-marketplace-service-rds-db-lib-billing-aws-billing-event';
// May contain unused imports in some cases
// @ts-ignore
import { SqlNullTime } from './sql-null-time';

/**
 * For AWS Marketplace
 * @export
 * @interface RevenueRecordDetailAwsRevenueRecordDetail
 */
export interface RevenueRecordDetailAwsRevenueRecordDetail {
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'action'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'agreementID'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'balanceImpacting'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'bankTraceID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'billingAddressID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'brokerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'buyerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'currency'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'dataFeedProductID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'disbursementBillingEventID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'endUserAccountID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'entitlementID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'fromAccountID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'id'?: string;
    /**
     * 
     * @type {SqlNullTime}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'insertDate'?: SqlNullTime;
    /**
     * 
     * @type {SqlNullTime}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'invoiceDate'?: SqlNullTime;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'invoiceID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'offerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'organizationID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'parentBillingEventID'?: string;
    /**
     * 
     * @type {SqlNullTime}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'paymentDueDate'?: SqlNullTime;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'productID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'toAccountID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'transactionReferenceID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'transactionType'?: string;
    /**
     * 
     * @type {SqlNullTime}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'usagePeriodEndDate'?: SqlNullTime;
    /**
     * 
     * @type {SqlNullTime}
     * @memberof RevenueRecordDetailAwsRevenueRecordDetail
     */
    'usagePeriodStartDate'?: SqlNullTime;
}

