/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GithubComSugerioMarketplaceServiceRdsDbLibBillingGcpChargeUsage } from './github-com-sugerio-marketplace-service-rds-db-lib-billing-gcp-charge-usage';

/**
 * For GCP Marketplace
 * @export
 * @interface RevenueRecordDetailGcpRevenueRecordDetail
 */
export interface RevenueRecordDetailGcpRevenueRecordDetail {
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'abandoned'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'accountID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'buyerID'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'charges'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'currency'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'dueVendor'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'entitlementID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'googleEntity'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'insightAccountID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'offerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'organizationID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'paymentSchedule'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'paymentType'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'prepayCredits'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'productID'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'refundBalanceDeductedThisMonth'?: number;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'refundBalanceOutstanding'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'refundReason'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'released'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'reportDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'resource'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'sku'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'trialUse'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'unit'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'usage'?: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'usedBy'?: string;
    /**
     * 
     * @type {number}
     * @memberof RevenueRecordDetailGcpRevenueRecordDetail
     */
    'withheld'?: number;
}

