/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { RevenueRecord } from './revenue-record';
// May contain unused imports in some cases
// @ts-ignore
import { RevenueReportType } from './revenue-report-type';

/**
 * 
 * @export
 * @interface RevenueReport
 */
export interface RevenueReport {
    /**
     * 
     * @type {string}
     * @memberof RevenueReport
     */
    'buyerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueReport
     */
    'entitlementID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueReport
     */
    'organizationID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueReport
     */
    'partner'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueReport
     */
    'productID'?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueReport
     */
    'reportDate'?: string;
    /**
     * 
     * @type {RevenueReportType}
     * @memberof RevenueReport
     */
    'reportType'?: RevenueReportType;
    /**
     * 
     * @type {Array<RevenueRecord>}
     * @memberof RevenueReport
     */
    'revenueRecords'?: Array<RevenueRecord>;
    /**
     * 
     * @type {string}
     * @memberof RevenueReport
     */
    'service'?: string;
}

