/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SalesforceCrmIntegrationCredential } from './salesforce-crm-integration-credential';
// May contain unused imports in some cases
// @ts-ignore
import { SharedSalesforceSyncFilter } from './shared-salesforce-sync-filter';

/**
 * 
 * @export
 * @interface SalesforceCrmIntegration
 */
export interface SalesforceCrmIntegration {
    /**
     * 
     * @type {SalesforceCrmIntegrationCredential}
     * @memberof SalesforceCrmIntegration
     */
    'credential'?: SalesforceCrmIntegrationCredential;
    /**
     * 
     * @type {Array<SharedSalesforceSyncFilter>}
     * @memberof SalesforceCrmIntegration
     */
    'filters'?: Array<SharedSalesforceSyncFilter>;
    /**
     * 
     * @type {string}
     * @memberof SalesforceCrmIntegration
     */
    'instanceUrl'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SalesforceCrmIntegration
     */
    'isSandbox'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SalesforceCrmIntegration
     */
    'secretKey'?: string;
    /**
     * User defined when setting up the integration
     * @type {string}
     * @memberof SalesforceCrmIntegration
     */
    'subdomain'?: string;
}

