/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ServicecontrolReportErrorStatus } from './servicecontrol-report-error-status';

/**
 * 
 * @export
 * @interface ServicecontrolReportError
 */
export interface ServicecontrolReportError {
    /**
     * OperationId: The Operation.operation_id value from the request.
     * @type {string}
     * @memberof ServicecontrolReportError
     */
    'operationId'?: string;
    /**
     * 
     * @type {ServicecontrolReportErrorStatus}
     * @memberof ServicecontrolReportError
     */
    'status'?: ServicecontrolReportErrorStatus;
}

