/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ServicecontrolStatus } from './servicecontrol-status';

/**
 * Status: Details of the error when processing the Operation.
 * @export
 * @interface ServicecontrolReportErrorStatus
 */
export interface ServicecontrolReportErrorStatus {
    /**
     * Code: The status code, which should be an enum value of google.rpc.Code.
     * @type {number}
     * @memberof ServicecontrolReportErrorStatus
     */
    'code'?: number;
    /**
     * Details: A list of messages that carry the error details. There is a common set of message types for APIs to use.
     * @type {Array<Array<number>>}
     * @memberof ServicecontrolReportErrorStatus
     */
    'details'?: Array<Array<number>>;
    /**
     * Message: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.
     * @type {string}
     * @memberof ServicecontrolReportErrorStatus
     */
    'message'?: string;
}

