/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SharedSalesforceSyncFilter
 */
export interface SharedSalesforceSyncFilter {
    /**
     * 
     * @type {string}
     * @memberof SharedSalesforceSyncFilter
     */
    'fieldName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedSalesforceSyncFilter
     */
    'operator'?: string;
    /**
     * 
     * @type {any}
     * @memberof SharedSalesforceSyncFilter
     */
    'value'?: any;
}

