/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SlackOAuthV2ResponseAuthedUser
 */
export interface SlackOAuthV2ResponseAuthedUser {
    /**
     * 
     * @type {string}
     * @memberof SlackOAuthV2ResponseAuthedUser
     */
    'access_token'?: string;
    /**
     * 
     * @type {number}
     * @memberof SlackOAuthV2ResponseAuthedUser
     */
    'expires_in'?: number;
    /**
     * 
     * @type {string}
     * @memberof SlackOAuthV2ResponseAuthedUser
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackOAuthV2ResponseAuthedUser
     */
    'refresh_token'?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackOAuthV2ResponseAuthedUser
     */
    'scope'?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackOAuthV2ResponseAuthedUser
     */
    'token_type'?: string;
}

