/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SlackOAuthResponseIncomingWebhook
 */
export interface SlackOAuthResponseIncomingWebhook {
    /**
     * 
     * @type {string}
     * @memberof SlackOAuthResponseIncomingWebhook
     */
    'channel'?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackOAuthResponseIncomingWebhook
     */
    'channel_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackOAuthResponseIncomingWebhook
     */
    'configuration_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackOAuthResponseIncomingWebhook
     */
    'url'?: string;
}

