/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SlackOAuthResponseIncomingWebhook } from './slack-oauth-response-incoming-webhook';
// May contain unused imports in some cases
// @ts-ignore
import { SlackOAuthV2ResponseAuthedUser } from './slack-oauth-v2-response-authed-user';
// May contain unused imports in some cases
// @ts-ignore
import { SlackOAuthV2ResponseEnterprise } from './slack-oauth-v2-response-enterprise';
// May contain unused imports in some cases
// @ts-ignore
import { SlackOAuthV2ResponseTeam } from './slack-oauth-v2-response-team';

/**
 * 
 * @export
 * @interface SlackIntegration
 */
export interface SlackIntegration {
    /**
     * 
     * @type {string}
     * @memberof SlackIntegration
     */
    'accessToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegration
     */
    'appId'?: string;
    /**
     * 
     * @type {SlackOAuthV2ResponseAuthedUser}
     * @memberof SlackIntegration
     */
    'authedUser'?: SlackOAuthV2ResponseAuthedUser;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegration
     */
    'botUserId'?: string;
    /**
     * 
     * @type {SlackOAuthV2ResponseEnterprise}
     * @memberof SlackIntegration
     */
    'enterprise'?: SlackOAuthV2ResponseEnterprise;
    /**
     * 
     * @type {number}
     * @memberof SlackIntegration
     */
    'expiresIn'?: number;
    /**
     * 
     * @type {SlackOAuthResponseIncomingWebhook}
     * @memberof SlackIntegration
     */
    'incomingWebhook'?: SlackOAuthResponseIncomingWebhook;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegration
     */
    'redirectUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegration
     */
    'refreshToken'?: string;
    /**
     * The scope of the access token. multiple scopes are separated by comma.
     * @type {string}
     * @memberof SlackIntegration
     */
    'scope'?: string;
    /**
     * 
     * @type {SlackOAuthV2ResponseTeam}
     * @memberof SlackIntegration
     */
    'team'?: SlackOAuthV2ResponseTeam;
    /**
     * 
     * @type {string}
     * @memberof SlackIntegration
     */
    'tokenType'?: string;
}

