/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GithubComAwsAwsSdkGoV2ServiceMarketplacemeteringTypesTag } from './github-com-aws-aws-sdk-go-v2-service-marketplacemetering-types-tag';

/**
 * 
 * @export
 * @interface TypesUsageAllocation
 */
export interface TypesUsageAllocation {
    /**
     * The set of tags that define the bucket of usage. For the bucket of items with no tags, this parameter can be left out.
     * @type {Array<GithubComAwsAwsSdkGoV2ServiceMarketplacemeteringTypesTag>}
     * @memberof TypesUsageAllocation
     */
    'tags'?: Array<GithubComAwsAwsSdkGoV2ServiceMarketplacemeteringTypesTag>;
    /**
     * The total quantity allocated to this bucket of usage.  This member is required.
     * @type {number}
     * @memberof TypesUsageAllocation
     */
    'allocatedUsageQuantity'?: number;
}

