/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Partner } from './partner';

/**
 * 
 * @export
 * @interface UsageMeteringDailyRecord
 */
export interface UsageMeteringDailyRecord {
    /**
     * 
     * @type {number}
     * @memberof UsageMeteringDailyRecord
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof UsageMeteringDailyRecord
     */
    'date'?: string;
    /**
     * The dimension key of the usage metering.
     * @type {string}
     * @memberof UsageMeteringDailyRecord
     */
    'key'?: string;
    /**
     * The partner where this usage metering daily record is from. Such as AWS, AZURE or GCP.
     * @type {Partner}
     * @memberof UsageMeteringDailyRecord
     */
    'partner'?: Partner;
    /**
     * 
     * @type {number}
     * @memberof UsageMeteringDailyRecord
     */
    'quantity'?: number;
}

