/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface UsageMeteringDimensionMappingValue
 */
export interface UsageMeteringDimensionMappingValue {
    /**
     * The convertion multiplier when mapping to the DimensionKey.
     * @type {number}
     * @memberof UsageMeteringDimensionMappingValue
     */
    'convertionMultiplier'?: number;
    /**
     * The dimension key of the usage metering.
     * @type {string}
     * @memberof UsageMeteringDimensionMappingValue
     */
    'dimensionKey'?: string;
}

