/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface UsageCount
 */
export interface UsageCount {
    /**
     * The count of this dimension usage records that are handled as credit.
     * @type {number}
     * @memberof UsageCount
     */
    'creditCount'?: number;
    /**
     * The count of this dimension usage records that are handled as included in IncludedBaseQuantity
     * @type {number}
     * @memberof UsageCount
     */
    'includedCount'?: number;
    /**
     * The count of this dimension usage records that are reported to cloud vendors.
     * @type {number}
     * @memberof UsageCount
     */
    'reportedCount'?: number;
}

