/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { EntitlementInfo } from './entitlement-info';
// May contain unused imports in some cases
// @ts-ignore
import { EntitlementTermInfo } from './entitlement-term-info';

/**
 * 
 * @export
 * @interface WorkloadEntitlementTerm
 */
export interface WorkloadEntitlementTerm {
    /**
     * 
     * @type {EntitlementTermInfo}
     * @memberof WorkloadEntitlementTerm
     */
    'info'?: EntitlementTermInfo;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlementTerm
     */
    'buyerID'?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkloadEntitlementTerm
     */
    'commitAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkloadEntitlementTerm
     */
    'creditAmount'?: number;
    /**
     * nullable
     * @type {string}
     * @memberof WorkloadEntitlementTerm
     */
    'endTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlementTerm
     */
    'entitlementID'?: string;
    /**
     * 
     * @type {EntitlementInfo}
     * @memberof WorkloadEntitlementTerm
     */
    'entitlementInfo'?: EntitlementInfo;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlementTerm
     */
    'externalEntitlementID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlementTerm
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlementTerm
     */
    'offerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlementTerm
     */
    'organizationID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlementTerm
     */
    'partner'?: WorkloadEntitlementTermPartnerEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlementTerm
     */
    'productID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlementTerm
     */
    'service'?: WorkloadEntitlementTermServiceEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlementTerm
     */
    'startTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkloadEntitlementTerm
     */
    'usedCommitAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkloadEntitlementTerm
     */
    'usedCreditAmount'?: number;
}

type WorkloadEntitlementTermPartnerEnum = 'AWS' | 'AZURE' | 'GCP'
type WorkloadEntitlementTermServiceEnum = 'MARKETPLACE'


