/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { OfferInfo } from './offer-info';
// May contain unused imports in some cases
// @ts-ignore
import { WorkloadMetaInfo } from './workload-meta-info';

/**
 * 
 * @export
 * @interface WorkloadOffer
 */
export interface WorkloadOffer {
    /**
     * 
     * @type {OfferInfo}
     * @memberof WorkloadOffer
     */
    'info'?: OfferInfo;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'creationTime'?: string;
    /**
     * nullable
     * @type {string}
     * @memberof WorkloadOffer
     */
    'endTime'?: string;
    /**
     * nullable
     * @type {string}
     * @memberof WorkloadOffer
     */
    'expireTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'externalID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'lastUpdateTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'lastUpdatedBy'?: string;
    /**
     * 
     * @type {WorkloadMetaInfo}
     * @memberof WorkloadOffer
     */
    'metaInfo'?: WorkloadMetaInfo;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'offerType'?: WorkloadOfferOfferTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'organizationID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'partner'?: WorkloadOfferPartnerEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'productID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'service'?: WorkloadOfferServiceEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkloadOffer
     */
    'status'?: WorkloadOfferStatusEnum;
}

type WorkloadOfferOfferTypeEnum = 'DEFAULT' | 'CONTRACT' | 'SUBSCRIPTION' | 'FREE_TRIAL' | 'FLAT_RATE' | 'PER_USER' | 'PRIVATE' | 'UNKNOWN'
type WorkloadOfferPartnerEnum = 'AWS' | 'AZURE' | 'GCP'
type WorkloadOfferServiceEnum = 'MARKETPLACE'
type WorkloadOfferStatusEnum = 'ACCEPTED' | 'PENDING_CREATE' | 'CREATE_FAILED' | 'CREATE_SUCCESS' | 'DRAFT' | 'EXPIRED' | 'PENDING_ACCEPTANCE' | 'PENDING_CANCEL' | 'CANCEL_FAILED' | 'CANCEL_SUCCESS'


