/* tslint:disable */
/* eslint-disable */
/**
 * Suger API
 * CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@suger.io
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { EntitlementInfo } from './entitlement-info';
// May contain unused imports in some cases
// @ts-ignore
import { WorkloadMetaInfo } from './workload-meta-info';

/**
 * 
 * @export
 * @interface WorkloadEntitlement
 */
export interface WorkloadEntitlement {
    /**
     * 
     * @type {EntitlementInfo}
     * @memberof WorkloadEntitlement
     */
    'info'?: EntitlementInfo;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'buyerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'creationTime'?: string;
    /**
     * nullable
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'endTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'entitlementTermID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'externalBuyerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'externalID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'externalProductID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'lastUpdateTime'?: string;
    /**
     * 
     * @type {WorkloadMetaInfo}
     * @memberof WorkloadEntitlement
     */
    'metaInfo'?: WorkloadMetaInfo;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'offerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'organizationID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'partner'?: WorkloadEntitlementPartnerEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'productID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'service'?: WorkloadEntitlementServiceEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'startTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'status'?: WorkloadEntitlementStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkloadEntitlement
     */
    'type'?: string;
}

type WorkloadEntitlementPartnerEnum = 'AWS' | 'AZURE' | 'GCP'
type WorkloadEntitlementServiceEnum = 'MARKETPLACE'
type WorkloadEntitlementStatusEnum = 'ACTIVE' | 'CANCELLED' | 'SUSPENDED' | 'PENDING_START' | 'UNKNOWN'


